name: My first pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4 
      - name: Build image
        run: docker build -t kserge2001/ciportofolio .
      - name: List images
        run: docker images